[package]
name = "pwease-give-streamer-notif"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
notifica = "3.0.x"
reqwest = "0.11.x"

[profile.dev.package."*"]
opt-level = 3
